install.packages("ppcor")
install.packages("ggplot2")
install.packages("gridextra")
install.packages("plotly")
install.packages(c('repr', 'IRdisplay', 'pbdZMQ', 'devtools'))
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec()
install.packages("olsrr") 
